services:
  game-postgres:
    container_name: game-postgres
    image: postgres:15
    volumes:
      - ../../volumes/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: game_database
